services:
    Gadget\Oracle\:
        autowire: true
        autoconfigure: true
        resource: '%kernel.project_dir%/vendor/mjfk23/gadget-oracle/src/'

    Gadget\Oracle\Command\Input\LogonOptions:
        arguments:
            $username: '%env(default::ORACLE_USER)%'
            $password: '%env(default::ORACLE_PASS)%'
            $connectIdentifier: '%env(default::ORACLE_CONN)%'
