parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Gsu\Biprod\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
