parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  PDO:
    class: \PDO
    arguments:
      $dsn: "%env(string:default::PDO_DSN)%"
      $username: "%env(string:default::PDO_USERNAME)%"
      $password: "%env(string:default::PDO_PASSWORD)%"
      $options:
        !php/const PDO::ATTR_ERRMODE: !php/const PDO::ERRMODE_EXCEPTION
        !php/const PDO::ATTR_DEFAULT_FETCH_MODE: !php/const PDO::FETCH_ASSOC
        !php/const PDO::ATTR_EMULATE_PREPARES: false

  Gsu\Biprod\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
