DROP TABLE D2L_OUTCOMES_ALIGNED_OBJECT;

CREATE TABLE D2L_OUTCOMES_ALIGNED_OBJECT (
  AlignedObjectType NUMBER(10,0) NOT NULL,
  AlignedObjectId NVARCHAR2(2000) NOT NULL
);

CREATE UNIQUE INDEX IDX_D2L_OUTCOMES_ALIGNED_OBJECT ON D2L_OUTCOMES_ALIGNED_OBJECT (AlignedObjectType, AlignedObjectId);
CREATE BITMAP INDEX IDX_D2L_OUTCOMES_ALIGNED_OBJECT_TYPE ON D2L_OUTCOMES_ALIGNED_OBJECT (AlignedObjectType);

QUIT;
