DROP TABLE GSU_SYLLABUS_VERIFICATION;

CREATE TABLE GSU_SYLLABUS_VERIFICATION (
  SeqNum                  NUMBER(10,0) NOT NULL,
  TermCode                VARCHAR2(6) NOT NULL,
  TermDescription         VARCHAR2(64) NOT NULL,
  CollegeCode             VARCHAR2(4) NOT NULL,
  CollegeDescription      VARCHAR2(64) NOT NULL,
  DepartmentCode          VARCHAR2(4) NOT NULL,
  DepartmentDescription   VARCHAR2(64) NOT NULL,
  CRN                     VARCHAR2(5) NOT NULL,
  SubjectCode             VARCHAR2(4) NOT NULL,
  CourseNumber            VARCHAR2(5) NOT NULL,
  SequenceNumber          VARCHAR2(3) NOT NULL,
  CourseTitle             VARCHAR2(64) NOT NULL,
  InstructorFirstName     VARCHAR2(120) DEFAULT NULL,
  InstructorLastName      VARCHAR2(120) DEFAULT NULL,
  InstructorEmail         VARCHAR2(30) DEFAULT NULL,
  VerifyStatus            VARCHAR2(10) NOT NULL,
  VerifyDate              DATE DEFAULT NULL,
  VerifyUser              VARCHAR2(30) DEFAULT NULL
);

CREATE UNIQUE INDEX IDX_GSU_SYLLABUS_VERIFICATION_SEQNUM ON GSU_SYLLABUS_VERIFICATION (SeqNum);
CREATE INDEX IDX_GSU_SYLLABUS_VERIFICATION_TERM_CRN ON GSU_SYLLABUS_VERIFICATION(TermCode,CRN);
CREATE INDEX IDX_GSU_SYLLABUS_VERIFICATION_SUBJ_CRSE_SEQ ON GSU_SYLLABUS_VERIFICATION(SubjectCode,CourseNumber,SequenceNumber);
CREATE INDEX IDX_GSU_SYLLABUS_VERIFICATION_INSTRUCTORNAME ON GSU_SYLLABUS_VERIFICATION(InstructorLastName,InstructorFirstName);
CREATE INDEX IDX_GSU_SYLLABUS_VERIFICATION_INSTRUCTOREMAIL ON GSU_SYLLABUS_VERIFICATION(InstructorEmail);
CREATE INDEX IDX_GSU_SYLLABUS_VERIFICATION_VERIFYDATE ON GSU_SYLLABUS_VERIFICATION(VerifyDate);
CREATE INDEX IDX_GSU_SYLLABUS_VERIFICATION_VERIFYUSER ON GSU_SYLLABUS_VERIFICATION(VerifyUser);
CREATE BITMAP INDEX IDX_GSU_SYLLABUS_VERIFICATION_TERMCODE ON GSU_SYLLABUS_VERIFICATION (TermCode);
CREATE BITMAP INDEX IDX_GSU_SYLLABUS_VERIFICATION_COLLEGECODE ON GSU_SYLLABUS_VERIFICATION (CollegeCode);
CREATE BITMAP INDEX IDX_GSU_SYLLABUS_VERIFICATION_DEPARTMENTCODE ON GSU_SYLLABUS_VERIFICATION (DepartmentCode);
CREATE BITMAP INDEX IDX_GSU_SYLLABUS_VERIFICATION_SUBJECTCODE ON GSU_SYLLABUS_VERIFICATION (SubjectCode);

QUIT;
